{
  "code": "200",
  "msg": "OK, all went through!",
  "data": [
    {
      "ein": "951916050",
      "charityName": "PLANNED PARENTHOOD PASADENA AND SAN GABRIEL VALLEY INC",
      "category": "Health - General and Rehabilitative",
      "url": "http://www.orghunter.com/organization/951916050",
      "donationUrl": "http://donate.makemydonation.org/donate/951916050",
      "eligibleCd": 1,
      "city": "ALTADENA",
      "state": "California",
      "zipCode": "91001-2463",
      "deductibilityCd": 1,
      "statusCd": 1,
      "start": 0,
      "rows": 20,
      "recordCount": 201,
      "score": 24.664864,
      "website": "",
      "missionStatement": "",
      "acceptingDonations": 1
    },
    {
      "ein": "626050064",
      "charityName": "PLANNED PARENTHOOD OF MIDDLE AND EAST TENNESSEE INC",
      "category": "Health - General and Rehabilitative",
      "url": "http://www.orghunter.com/organization/626050064",
      "donationUrl": "http://donate.makemydonation.org/donate/626050064",
      "eligibleCd": 1,
      "city": "NASHVILLE",
      "state": "Tennessee",
      "zipCode": "37228-1516",
      "deductibilityCd": 1,
      "statusCd": 1,
      "start": 0,
      "rows": 20,
      "recordCount": 201,
      "score": 24.664864,
      "website": "www.ppmet.org",
      "missionStatement": "PPMET provides access to reproductive and sexual healthcare services and sex education programs, and advocates for public policies to protect reproductive rights and services.",
      "acceptingDonations": 1
    },
    {
      "ein": "201987331",
      "charityName": "PLANNED PARENTHOOD PUBLIC POLICY NETWORK OF THE NORTHWEST",
      "category": "Health - General and Rehabilitative",
      "url": "http://www.orghunter.com/organization/201987331",
      "donationUrl": "http://donate.makemydonation.org/donate/201987331",
      "eligibleCd": 1,
      "city": "SEATTLE",
      "state": "Washington",
      "zipCode": "98122-2959",
      "deductibilityCd": 1,
      "statusCd": 1,
      "start": 0,
      "rows": 20,
      "recordCount": 201,
      "score": 24.664864,
      "website": "",
      "missionStatement": "",
      "acceptingDonations": 1
    },
    {
      "ein": "581484820",
      "charityName": "PLANNED PARENTHOOD OF CENTRAL NORTH CAROLINA INC",
      "category": "Health - General and Rehabilitative",
      "url": "http://www.orghunter.com/organization/581484820",
      "donationUrl": "http://donate.makemydonation.org/donate/581484820",
      "eligibleCd": 1,
      "city": "CHAPEL HILL",
      "state": "North Carolina",
      "zipCode": "27514-5876",
      "deductibilityCd": 1,
      "statusCd": 1,
      "start": 0,
      "rows": 20,
      "recordCount": 201,
      "score": 24.664864,
      "website": "www.ppcentralnc.org",
      "missionStatement": "Provides healthcare, educational programs & advocacy to help reduce unintended pregnancy & sexually transmitted infections, especially among teens, people with limited incomes, & the uninsured.",
      "acceptingDonations": 1
    },
    {
      "ein": "251876210",
      "charityName": "PLANNED PARENTHOOD OF WESTERN",
      "category": "Not Provided",
      "url": "http://www.orghunter.com/organization/251876210",
      "donationUrl": "http://donate.makemydonation.org/donate/251876210",
      "eligibleCd": 0,
      "city": "PITTSBURGH",
      "state": "Pennsylvania",
      "zipCode": "15222-3783",
      "deductibilityCd": 0,
      "statusCd": 4,
      "start": 0,
      "rows": 20,
      "recordCount": 201,
      "score": 24.664864,
      "website": "",
      "missionStatement": "",
      "acceptingDonations": 0
    },
    {
      "ein": "860661959",
      "charityName": "PLANNED PARENTHOOD OF SOUTHERN",
      "category": "Not Provided",
      "url": "http://www.orghunter.com/organization/860661959",
      "donationUrl": "http://donate.makemydonation.org/donate/860661959",
      "eligibleCd": 0,
      "city": "TUCSON",
      "state": "Arizona",
      "zipCode": "85701-2005",
      "deductibilityCd": 0,
      "statusCd": 4,
      "start": 0,
      "rows": 20,
      "recordCount": 201,
      "score": 24.664864,
      "website": "",
      "missionStatement": "",
      "acceptingDonations": 0
    },
    {
      "ein": "941583439",
      "charityName": "PLANNED PARENTHOOD MAR MONTE INC",
      "category": "Health - General and Rehabilitative",
      "url": "http://www.orghunter.com/organization/941583439",
      "donationUrl": "http://donate.makemydonation.org/donate/941583439",
      "eligibleCd": 1,
      "city": "SAN JOSE",
      "state": "California",
      "zipCode": "95126-2203",
      "deductibilityCd": 1,
      "statusCd": 1,
      "start": 0,
      "rows": 20,
      "recordCount": 201,
      "score": 24.664864,
      "website": "www.ppmarmonte.org",
      "missionStatement": "Accessible, personalized, affordable reproductive and primary health care, educational programs and advocacy for women, men, teens and families throughout central and northern California.",
      "acceptingDonations": 1
    },
    {
      "ein": "870288909",
      "charityName": "PLANNED PARENTHOOD ASSOCIATION OF UTAH",
      "category": "Health - General and Rehabilitative",
      "url": "http://www.orghunter.com/organization/870288909",
      "donationUrl": "http://donate.makemydonation.org/donate/870288909",
      "eligibleCd": 1,
      "city": "SALT LAKE CTY",
      "state": "Utah",
      "zipCode": "84102-3478",
      "deductibilityCd": 1,
      "statusCd": 1,
      "start": 0,
      "rows": 20,
      "recordCount": 201,
      "score": 24.664864,
      "website": "www.ppau.org",
      "missionStatement": "Provides subsidized family planning services, including contraception, screening and treatment of sexually transmitted infections, screenings for cancers of the reproductive system, and sexuality education.",
      "acceptingDonations": 1
    },
    {
      "ein": "232630153",
      "charityName": "PLANNED PARENTHOOD OF THE SUSQUEHANNA VALLEY ACTION FUND",
      "category": "Not Provided",
      "url": "http://www.orghunter.com/organization/232630153",
      "donationUrl": "http://donate.makemydonation.org/donate/232630153",
      "eligibleCd": 0,
      "city": "TREXLERTOWN",
      "state": "Pennsylvania",
      "zipCode": "18087-0813",
      "deductibilityCd": 2,
      "statusCd": 4,
      "start": 0,
      "rows": 20,
      "recordCount": 201,
      "score": 24.664864,
      "website": "",
      "missionStatement": "",
      "acceptingDonations": 0
    },
    {
      "ein": "570409058",
      "charityName": "PLANNED PARENTHOOD OF KERSHAW",
      "category": "Not Provided",
      "url": "http://www.orghunter.com/organization/570409058",
      "donationUrl": "http://donate.makemydonation.org/donate/570409058",
      "eligibleCd": 0,
      "city": "CAMDEN",
      "state": "South Carolina",
      "zipCode": "29020-0000",
      "deductibilityCd": 0,
      "statusCd": 4,
      "start": 0,
      "rows": 20,
      "recordCount": 201,
      "score": 24.664864,
      "website": "",
      "missionStatement": "",
      "acceptingDonations": 0
    },
    {
      "ein": "221539559",
      "charityName": "PLANNED PARENTHOOD OF METROPOLITAN NEW JERSEY INC",
      "category": "Health - General and Rehabilitative",
      "url": "http://www.orghunter.com/organization/221539559",
      "donationUrl": "http://donate.makemydonation.org/donate/221539559",
      "eligibleCd": 1,
      "city": "NEWARK",
      "state": "New Jersey",
      "zipCode": "07102-0000",
      "deductibilityCd": 1,
      "statusCd": 1,
      "start": 0,
      "rows": 20,
      "recordCount": 201,
      "score": 24.664864,
      "website": "",
      "missionStatement": "",
      "acceptingDonations": 1
    },
    {
      "ein": "133834672",
      "charityName": "NEW YORK STATE AFFILIATES OF PLANNED PARENTHOOD INC",
      "category": "Health - General and Rehabilitative",
      "url": "http://www.orghunter.com/organization/133834672",
      "donationUrl": "http://donate.makemydonation.org/donate/133834672",
      "eligibleCd": 0,
      "city": "ROCHESTER",
      "state": "New York",
      "zipCode": "14605-2929",
      "deductibilityCd": 1,
      "statusCd": 0,
      "start": 0,
      "rows": 20,
      "recordCount": 201,
      "score": 24.664864,
      "website": "",
      "missionStatement": "",
      "acceptingDonations": 0
    },
    {
      "ein": "520607930",
      "charityName": "PLANNED PARENTHOOD OF MARYLAND INC",
      "category": "Health - General and Rehabilitative",
      "url": "http://www.orghunter.com/organization/520607930",
      "donationUrl": "http://donate.makemydonation.org/donate/520607930",
      "eligibleCd": 1,
      "city": "BALTIMORE",
      "state": "Maryland",
      "zipCode": "21201-3610",
      "deductibilityCd": 1,
      "statusCd": 1,
      "start": 0,
      "rows": 20,
      "recordCount": 201,
      "score": 24.664864,
      "website": "www.plannedparenthood.org/maryland",
      "missionStatement": "Helping individuals make informed decisions about their reproductive health, family planning options, and sexuality through medical services, education, training and advocacy.",
      "acceptingDonations": 1
    },
    {
      "ein": "356504391",
      "charityName": "ROBERT EFROYMSON TRUST FOR PLANNED PARENTHOOD & THE INDIANAPOLIS FDN",
      "category": "Health - General and Rehabilitative",
      "url": "http://www.orghunter.com/organization/356504391",
      "donationUrl": "http://donate.makemydonation.org/donate/356504391",
      "eligibleCd": 1,
      "city": "CHICAGO",
      "state": "Illinois",
      "zipCode": "60603-2300",
      "deductibilityCd": 1,
      "statusCd": 1,
      "start": 0,
      "rows": 20,
      "recordCount": 201,
      "score": 24.664864,
      "website": "",
      "missionStatement": "",
      "acceptingDonations": 1
    },
    {
      "ein": "146004167",
      "charityName": "PLANNED PARENTHOOD MOHAWK HUDSON INC",
      "category": "Health - General and Rehabilitative",
      "url": "http://www.orghunter.com/organization/146004167",
      "donationUrl": "http://donate.makemydonation.org/donate/146004167",
      "eligibleCd": 1,
      "city": "SCHENECTADY",
      "state": "New York",
      "zipCode": "12307-1508",
      "deductibilityCd": 1,
      "statusCd": 1,
      "start": 0,
      "rows": 20,
      "recordCount": 201,
      "score": 24.664864,
      "website": "www.plannedparenthood.org/ppmh",
      "missionStatement": "Reproductive healthcare for women and men throughout life; age appropriate sex education and counseling to prevent unintended pregnancy, sexually transmitted infections,HIV,espically among teens.",
      "acceptingDonations": 1
    },
    {
      "ein": "132621497",
      "charityName": "PLANNED PARENTHOOD OF NEW YORK CITY INC",
      "category": "Health - General and Rehabilitative",
      "url": "http://www.orghunter.com/organization/132621497",
      "donationUrl": "http://donate.makemydonation.org/donate/132621497",
      "eligibleCd": 1,
      "city": "NEW YORK",
      "state": "New York",
      "zipCode": "10012-2413",
      "deductibilityCd": 1,
      "statusCd": 1,
      "start": 0,
      "rows": 20,
      "recordCount": 201,
      "score": 24.664864,
      "website": "www.ppnyc.org",
      "missionStatement": "Provides family planning services, education and counseling to thousands of New Yorkers while working to preserve and defend reproductive rights for all Americans.",
      "acceptingDonations": 1
    },
    {
      "ein": "593092996",
      "charityName": "PLANNED PARENTHOOD OF GREATER ORLANDO INC",
      "category": "Health - General and Rehabilitative",
      "url": "http://www.orghunter.com/organization/593092996",
      "donationUrl": "http://donate.makemydonation.org/donate/593092996",
      "eligibleCd": 0,
      "city": "ORLANDO",
      "state": "Florida",
      "zipCode": "32805-3646",
      "deductibilityCd": 1,
      "statusCd": 0,
      "start": 0,
      "rows": 20,
      "recordCount": 201,
      "score": 24.664864,
      "website": "",
      "missionStatement": "",
      "acceptingDonations": 0
    },
    {
      "ein": "311266132",
      "charityName": "PLANNED PARENTHOOD OF MIAMI VALLEY FOUNDATION",
      "category": "Health - General and Rehabilitative",
      "url": "http://www.orghunter.com/organization/311266132",
      "donationUrl": "http://donate.makemydonation.org/donate/311266132",
      "eligibleCd": 1,
      "city": "DAYTON",
      "state": "Ohio",
      "zipCode": "45402-3011",
      "deductibilityCd": 1,
      "statusCd": 1,
      "start": 0,
      "rows": 20,
      "recordCount": 201,
      "score": 24.664864,
      "website": "",
      "missionStatement": "",
      "acceptingDonations": 1
    },
    {
      "ein": "431621500",
      "charityName": "PLANNED PARENTHOOD GREAT PLAINS VOTES",
      "category": "Not Provided",
      "url": "http://www.orghunter.com/organization/431621500",
      "donationUrl": "http://donate.makemydonation.org/donate/431621500",
      "eligibleCd": 0,
      "city": "OVERLAND PARK",
      "state": "Kansas",
      "zipCode": "66211-1303",
      "deductibilityCd": 2,
      "statusCd": 0,
      "start": 0,
      "rows": 20,
      "recordCount": 201,
      "score": 24.664864,
      "website": "",
      "missionStatement": "",
      "acceptingDonations": 0
    },
    {
      "ein": "264715618",
      "charityName": "NEVADA EDUCATION FUND FOR PLANNED PARENTHOOD AFFILIATES INCORPORATED",
      "category": "Civil Rights, Social Action, Advocacy",
      "url": "http://www.orghunter.com/organization/264715618",
      "donationUrl": "http://donate.makemydonation.org/donate/264715618",
      "eligibleCd": 1,
      "city": "RENO",
      "state": "Nevada",
      "zipCode": "89509-3468",
      "deductibilityCd": 1,
      "statusCd": 1,
      "start": 0,
      "rows": 20,
      "recordCount": 201,
      "score": 24.664864,
      "website": "",
      "missionStatement": "",
      "acceptingDonations": 1
    }
  ]
}